#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Kaggle API credentials and a proven end-to-end submission.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

COMPETITION="playground-series-s6e9"
KAGGLE_DIR="$HOME/.kaggle"
KAGGLE_JSON="$KAGGLE_DIR/kaggle.json"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KAGGLE_BIN="kaggle"

banner "Kaggle submission setup — $COMPETITION"

# ── Stage 1 — install the CLI ─────────────────────────────────────────────
stage "Install the kaggle CLI"
say "The project .venv has a broken pip, so we install the CLI standalone with uv."
note "Nothing is installed into the project venv."

if command -v kaggle >/dev/null 2>&1; then
  say "kaggle is already on PATH: $(command -v kaggle)"
else
  if ! command -v uv >/dev/null 2>&1; then
    warn "uv not found. Install it with: brew install uv"
    SKIPPED+=("install uv, then re-run this wizard")
    exit 1
  fi
  say "Installing…"
  uv tool install kaggle
fi

if ! command -v kaggle >/dev/null 2>&1; then
  # uv installs tools into ~/.local/bin, which may not be on PATH yet.
  if [[ -x "$HOME/.local/bin/kaggle" ]]; then
    KAGGLE_BIN="$HOME/.local/bin/kaggle"
    warn "kaggle installed but ~/.local/bin is not on your PATH."
    note "This wizard will use the full path. To fix it permanently, add to ~/.zshrc:"
    note '  export PATH="$HOME/.local/bin:$PATH"'
    SKIPPED+=('add export PATH="$HOME/.local/bin:$PATH" to ~/.zshrc')
  else
    warn "kaggle still not found after install — stopping."
    exit 1
  fi
fi
say "Using: $KAGGLE_BIN"
pause "Press Enter to continue"

# ── Stage 2 — API credentials ─────────────────────────────────────────────
stage "Generate your Kaggle API token"

if [[ -f "$KAGGLE_JSON" ]]; then
  say "Found existing credentials at $KAGGLE_JSON"
  if ! confirm "Replace them with a fresh token?"; then
    say "Keeping the existing token."
    pause "Press Enter to continue"
  else
    rm -f "$KAGGLE_JSON"
  fi
fi

if [[ ! -f "$KAGGLE_JSON" ]]; then
  open_url "https://www.kaggle.com/settings"
  step "Sign in if prompted."
  step "Scroll to the 'API' section."
  step "Click 'Create New Token' — your browser downloads kaggle.json."
  note "If you already had a token, this revokes the old one."
  pause "Press Enter once kaggle.json has downloaded"

  mkdir -p "$KAGGLE_DIR"
  FOUND=""
  for candidate in "$HOME/Downloads/kaggle.json" "$HOME/Desktop/kaggle.json" "$REPO_ROOT/kaggle.json"; do
    [[ -f "$candidate" ]] && { FOUND="$candidate"; break; }
  done

  if [[ -n "$FOUND" ]]; then
    say "Found it at $FOUND"
    mv "$FOUND" "$KAGGLE_JSON"
  else
    warn "Couldn't find kaggle.json automatically."
    say "Open the downloaded file — it looks like {\"username\":\"...\",\"key\":\"...\"}"
    ask KAGGLE_USERNAME "Paste the username value:"
    ask_secret KAGGLE_KEY "Paste the key value (hidden):"
    printf '{"username":"%s","key":"%s"}\n' "$KAGGLE_USERNAME" "$KAGGLE_KEY" > "$KAGGLE_JSON"
  fi

  chmod 600 "$KAGGLE_JSON"
  printf '  %s✓%s credentials at %s (mode 600)\n' "$GREEN" "$RESET" "$KAGGLE_JSON"
fi
pause "Press Enter to continue"

# ── Stage 3 — accept the competition rules ────────────────────────────────
stage "Accept the competition rules"
say "The API rejects submissions until the rules are accepted in the browser."
say "There is no way to do this from the command line."
open_url "https://www.kaggle.com/competitions/$COMPETITION/rules"
step "Read the rules, then click 'I Understand and Accept' at the bottom."
note "Already accepted? The button is replaced by a confirmation — nothing to do."
pause "Press Enter once the rules are accepted"

# ── Stage 4 — verify authentication ───────────────────────────────────────
stage "Verify authentication and fetch the competition files"
say "Listing the competition proves the token works and the rules are accepted."
if "$KAGGLE_BIN" competitions list -s "playground-series-s6e9" 2>&1 | grep -q "$COMPETITION"; then
  printf '  %s✓%s authenticated, competition visible\n' "$GREEN" "$RESET"
else
  warn "Could not see the competition. Usual causes:"
  note "  - the token is wrong or was revoked (re-run stage 2)"
  note "  - the rules were not accepted (re-run stage 3)"
  exit 1
fi

say ""
say "Data files are already in data/ — we only re-download if you want to verify."
if confirm "Download the competition files to confirm access?"; then
  TMPD=$(mktemp -d)
  "$KAGGLE_BIN" competitions download -c "$COMPETITION" -p "$TMPD"
  say "Downloaded to $TMPD:"
  ls -lh "$TMPD"
  note "Delete it when you're done: rm -rf $TMPD"
fi
pause "Press Enter to continue"

# ── Stage 5 — prove a submission end to end ───────────────────────────────
stage "Submit sample_submission.csv as a calibration point"
SAMPLE="$REPO_ROOT/data/sample_submission.csv"
if [[ ! -f "$SAMPLE" ]]; then
  warn "Not found: $SAMPLE"
  SKIPPED+=("submit a calibration file once data/sample_submission.csv exists")
else
  say "This file predicts the constant 0.1746450 (the train positive rate) for every row."
  say "Its AUC is 0.5 by construction — the point is to prove the pipe works,"
  say "and it costs 1 of your 10 daily submissions."
  if confirm "Submit it now?"; then
    "$KAGGLE_BIN" competitions submit -c "$COMPETITION" \
      -f "$SAMPLE" -m "wizard calibration: constant baseline"
    say ""
    say "Waiting for Kaggle to score it…"
    for _ in 1 2 3 4 5 6 7 8 9 10; do
      sleep 6
      OUT=$("$KAGGLE_BIN" competitions submissions -c "$COMPETITION" --csv 2>/dev/null || true)
      if printf '%s' "$OUT" | grep -qi "complete"; then break; fi
      printf '  %s.%s' "$DIM" "$RESET"
    done
    printf '\n\n'
    say "Your submissions so far:"
    "$KAGGLE_BIN" competitions submissions -c "$COMPETITION" | head -10
  else
    say "Skipped — the credentials still work, you just haven't spent a slot."
  fi
fi

printf '\n'
say "From here, every submission is one command:"
note "  $KAGGLE_BIN competitions submit -c $COMPETITION -f <file.csv> -m \"<message>\""
say "Check your remaining daily quota (10/day, 2 final submissions count):"
note "  $KAGGLE_BIN competitions submissions -c $COMPETITION"
pause "Press Enter to finish"

finish
